version: '3.9'
services:
  kolikargo-backend:
    container_name: kolikargo-backend
    image: kolikargo-backend:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    networks:
      - kolikargo-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    tty: true
    command: "yarn start:dev"
    env_file: .env
    environment:
      MONGO_URL: mongodb
      MONGODB_USER: koliadminmng!
      MONGODB_PASSWORD: koliPasswd123mng!

  mongodb:
    image: mongo:latest
    container_name: server-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=koliadminmng!
      - MONGO_INITDB_ROOT_PASSWORD=koliPasswd123mng!
    volumes:
      - mongodata:/data/db
    networks:
      - kolikargo-network
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    container_name: server-mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=koliadminmng!
      - ME_CONFIG_MONGODB_ADMINPASSWORD=koliPasswd123mng!
      - ME_CONFIG_BASICAUTH_USERNAME=koliadmin
      - ME_CONFIG_BASICAUTH_PASSWORD=KoliAdm123!
    volumes:
      - .mongodata:/data/db
    depends_on:
      - mongodb
    networks:
      - kolikargo-network
    ports:
      - "8081:8081"
    healthcheck:
      test: wget --quiet --tries=3 --spider http://koliadmin:KoliAdm123!@localhost:8081 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  mongo-express-prod:
    image: mongo-express:latest
    container_name: server-mongo-express-prod
    env_file:
      .env
    ports:
      - "8082:8082"
    volumes:
      - ./.mongoconfig/db-client.ca.crt:/etc/db-client.ca.crt:ro
      - ./.mongoconfig/config.js:/node_modules/mongo-express/config.js:ro
    networks:
      - kolikargo-network
    healthcheck:
      test: wget --quiet --tries=3 --spider http://koliadmin:KoliAdm123!@localhost:8082 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped


volumes:
  mongodata:
    name: mongodata

networks:
  kolikargo-network:
